#!/bin/sh
#$ -S /bin/sh
#$ -o /usr/users/weisongl/qstaterr/std_$JOB_ID.out
#$ -e /usr/users/weisongl/qstaterr/std_$JOB_ID.err
echo $JOB_NAME $JOB_ID `hostname` `date` >> ~/q.log
# Get the host machine for your job
hostname
# Begin the commands to execute


cd /usr/users/weisongl/dielectric_constant/HS

t=`awk -v t=$4 'BEGIN {print t/1.0;}'`
p=`awk -v p=$3 'BEGIN {print p/100.0;}'`
m=`awk -v m=$2 'BEGIN {print m*1.0;}'`
N=`awk -v N=$1 'BEGIN {print N;}'`

# safeappend outputN${N}m${m}T${t}p${p}

safeappend outputN${N}m${m}T${t}p${p}  java -cp ~/DHS.jar etomica.dielectric.DHS_NVT -dielectricOutside 100000000000 -steps 100000000 -numberMolecules $N -temperature $t -dipoleStrength2 $m -density $p


